# Sentry in Docker
# https://hub.docker.com/_/sentry/
#
version: '3.1'
services:
  redis:
    image: redis:5.0.6-alpine
    networks:
    - net_sentry
    volumes:
    - vol_redis:/data

  postgres:
    image: postgres:11.5-alpine
    environment:
    - POSTGRES_USER=sentry
    - POSTGRES_PASSWORD=secret
    networks:
    - net_sentry
    volumes:
    - vol_postgres:/var/lib/postgresql/data

  web:
    image: sentry:9.1.2
    env_file: sentry.env
    command: /bin/bash -c "sentry upgrade --noinput && sentry run web"
    ports:
    - 9000:9000
    networks:
    - net_sentry
    volumes:
    - vol_sentry_web:/var/lib/sentry/files
    depends_on:
    - redis
    - postgres

  cron:
    image: sentry:9.1.2
    env_file: sentry.env
    command: /bin/bash -c "sentry run cron"
    networks:
    - net_sentry
    volumes:
    - vol_sentry_cron:/var/lib/sentry/files
    depends_on:
    - web

  worker:
    image: sentry:9.1.2
    env_file: sentry.env
    environment:
    - C_FORCE_ROOT=yes
    command: /bin/bash -c "sentry run worker"
    networks:
    - net_sentry
    volumes:
    - vol_sentry_worker:/var/lib/sentry/files
    depends_on:
    - web

networks:
  net_sentry:

volumes:
  vol_redis:
  vol_postgres:
  vol_sentry_web:
  vol_sentry_cron:
  vol_sentry_worker:

