# Sentry in Docker
# https://hub.docker.com/_/sentry/
#
version: '3.1'
services:
  redis:
    image: redis:5.0.6-alpine
    networks:
    - net_sentry
    volumes:
    - vol_redis:/data

  postgres:
    image: postgres:11.5-alpine
    environment:
    - POSTGRES_USER=sentry
    - POSTGRES_PASSWORD=secret
    networks:
    - net_sentry
    volumes:
    - vol_postgres:/var/lib/postgresql/data

  server:
    image: sentry:9.1.2
    environment:
    - SENTRY_SECRET_KEY=y#(dmr6@vx603nd^1=s2=z_7vplow&(+aar#1hlnjp&%0p6ncv
    - SENTRY_REDIS_HOST=redis
    - SENTRY_REDIS_PORT=6379
    - SENTRY_REDIS_DB=0
    - SENTRY_POSTGRES_HOST=postgres
    - SENTRY_POSTGRES_PORT=5432
    - SENTRY_DB_NAME=postgres
    - SENTRY_DB_USER=sentry
    - SENTRY_DB_PASSWORD=secret
    command: /bin/bash -c "sentry upgrade --noinput && sentry run web"
    ports:
    - 9000:9000
    networks:
    - net_sentry
    volumes:
    - vol_sentry:/var/lib/sentry/files
    depends_on:
    - redis
    - postgres

networks:
  net_sentry:

volumes:
  vol_redis:
  vol_postgres:
  vol_sentry:

